### ISSUE TITLE
specifying network via commands does not work properly

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/LargestSubnetwork#1]
Interestingly, the largest component is found in the current network and then the code attempts to select those nodes in the specified network. 

Steps to reproduce:
1. Open galFiltered
2. Select some of the smaller components manuall and create a subnetwork
3. Run this command: `network select component network="galFiltered.sif"`

You'll notice that the largeset component of the subnetwork is selected in the parent network!!

**Comment by yihangx** [comment]
Fixed.
