### ISSUE TITLE
return selected nodes via commands

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/LargestSubnetwork#2]
Typical of other `select` commands, it's a nice feature to return the list of selected nodes.

To see an example:
1. Open galFiltered
2. Select one node
3. Run `network select nodeList="selected" firstNeighbors="any"`

You'll see the return includes a list of nodes in JSON format. This is very useful for automation use cases.

RCy3 and py4cy can parse this return to provide a nice list for scripters.

**Comment by yihangx** [comment]
Fixed.
